name: Install Wine on OS X
description: Install Wine on OS X

runs:
  using: "composite"
  steps:
    # wine@staging v9.17
    - run: |
        curl -L ${{env.WINE_CASK}} > wine@staging.rb;
        brew install --cask wine@staging.rb;
        rm wine@staging.rb;
      shell: bash
      env: 
        WINE_CASK: https://raw.githubusercontent.com/Homebrew/homebrew-cask/2f29727c9961e8159df6dc19db315bc7783a4b99/Casks/w/wine%40staging.rb
   
    # We can't use /usr/share/wine/mono because it's read-only
    # We can't use /opt/wine/mono because it's read-only
    - run: |
        mkdir -p ~/.wine/share/wine/mono
        curl -L -o mono.tar.xz ${{env.WINE_MONO}}
        tar -xf mono.tar.xz -C ~/.wine/share/wine/mono
      shell: bash
      env: 
        WINE_MONO: https://github.com/madewokherd/wine-mono/releases/download/wine-mono-9.3.0/wine-mono-9.3.0-x86.tar.xz