name: Upload Test Results
description: Upload the test results for the specified image and build configuration

inputs:
  osimage:
    description: 'The image to use'
    required: true
  architecture:
    description: 'The architecture to use'
    required: true
  build_configuration:
    description: 'The build configuration to use'
    required: true
  experimental:
    description: 'Whether the tests are mandatory for the build to pass'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: ${{success() || failure()}}
      with:
        name: ${{(inputs.experimental == 'true' && 'experimental-') || ''}}test-results-${{inputs.image}}-${{inputs.architecture}}-${{inputs.build_configuration}}
        path: '**/*.trx'
        if-no-files-found: ${{(inputs.experimental == 'true' && 'ignore') || 'warn'}}
        retention-days: 1
